import { User, columns } from "./Columns";
import { DataTable } from "./DataTable";

const getData = async (): Promise<User[] | any[]> => {
  return [
    {
      id: "1",
      username: "john.doe",
      email: "john.doe@mail.com",
      phone: "+1 234 5678",
      role: "Admin",
      joinedOn: "25.07.2023",
      location: "New York, NY",
      userStatus: "Finished",
    },
    {
      id: "2",
      username: "sarah.smith",
      email: "sarah.smith@mail.com",
      phone: "+44 7456 7890",
      role: "User",
      joinedOn: "12.06.2023",
      location: "London, UK",
      userStatus: "Active",
    },
    {
      id: "3",
      username: "michael.brown",
      email: "michael.brown@mail.com",
      phone: "+1 567 2345",
      role: "Manager",
      joinedOn: "03.02.2024",
      location: "Chicago, IL",
      userStatus: "Pending",
    },
    {
      id: "4",
      username: "emily.jones",
      email: "emily.jones@mail.com",
      phone: "+33 612 345 678",
      role: "Editor",
      joinedOn: "19.08.2023",
      location: "Paris, FR",
      userStatus: "Active",
    },
    {
      id: "5",
      username: "david.wilson",
      email: "david.wilson@mail.com",
      phone: "+1 321 6547",
      role: "User",
      joinedOn: "01.01.2023",
      location: "Los Angeles, CA",
      userStatus: "Banned",
    },
    {
      id: "6",
      username: "anna.kim",
      email: "anna.kim@mail.com",
      phone: "+82 10 2345 6789",
      role: "Admin",
      joinedOn: "11.03.2024",
      location: "Seoul, KR",
      userStatus: "Active",
    },
    {
      id: "7",
      username: "james.lee",
      email: "james.lee@mail.com",
      phone: "+61 412 345 678",
      role: "User",
      joinedOn: "22.04.2023",
      location: "Sydney, AU",
      userStatus: "Finished",
    },
    {
      id: "8",
      username: "olivia.martin",
      email: "olivia.martin@mail.com",
      phone: "+49 151 2345 6789",
      role: "Editor",
      joinedOn: "15.05.2023",
      location: "Berlin, DE",
      userStatus: "Active",
    },
    {
      id: "9",
      username: "daniel.garcia",
      email: "daniel.garcia@mail.com",
      phone: "+34 612 987 654",
      role: "Manager",
      joinedOn: "29.11.2023",
      location: "Madrid, ES",
      userStatus: "Pending",
    },
    {
      id: "10",
      username: "sophia.rodriguez",
      email: "sophia.rodriguez@mail.com",
      phone: "+52 55 1234 5678",
      role: "User",
      joinedOn: "06.09.2023",
      location: "Mexico City, MX",
      userStatus: "Active",
    },
    {
      id: "11",
      username: "william.johnson",
      email: "william.johnson@mail.com",
      phone: "+1 987 6543",
      role: "Admin",
      joinedOn: "18.07.2023",
      location: "Boston, MA",
      userStatus: "Active",
    },
    {
      id: "12",
      username: "mia.davis",
      email: "mia.davis@mail.com",
      phone: "+39 345 678 9012",
      role: "User",
      joinedOn: "25.12.2023",
      location: "Rome, IT",
      userStatus: "Finished",
    },
    {
      id: "13",
      username: "ethan.white",
      email: "ethan.white@mail.com",
      phone: "+1 456 7890",
      role: "Manager",
      joinedOn: "09.10.2023",
      location: "Houston, TX",
      userStatus: "Banned",
    },
    {
      id: "14",
      username: "ava.thompson",
      email: "ava.thompson@mail.com",
      phone: "+46 70 123 4567",
      role: "Editor",
      joinedOn: "17.01.2024",
      location: "Stockholm, SE",
      userStatus: "Active",
    },
    {
      id: "15",
      username: "jack.moore",
      email: "jack.moore@mail.com",
      phone: "+1 202 3456",
      role: "User",
      joinedOn: "08.08.2023",
      location: "Washington, DC",
      userStatus: "Pending",
    },
    {
      id: "16",
      username: "isabella.taylor",
      email: "isabella.taylor@mail.com",
      phone: "+7 912 345 6789",
      role: "Admin",
      joinedOn: "04.04.2023",
      location: "Moscow, RU",
      userStatus: "Active",
    },
    {
      id: "17",
      username: "alexander.clark",
      email: "alexander.clark@mail.com",
      phone: "+1 310 4567",
      role: "User",
      joinedOn: "13.03.2024",
      location: "San Francisco, CA",
      userStatus: "Finished",
    },
    {
      id: "18",
      username: "chloe.harris",
      email: "chloe.harris@mail.com",
      phone: "+1 415 6789",
      role: "Manager",
      joinedOn: "21.11.2023",
      location: "Seattle, WA",
      userStatus: "Pending",
    },
    {
      id: "19",
      username: "benjamin.adams",
      email: "benjamin.adams@mail.com",
      phone: "+1 702 2345",
      role: "Editor",
      joinedOn: "14.02.2024",
      location: "Las Vegas, NV",
      userStatus: "Active",
    },
    {
      id: "20",
      username: "ella.evans",
      email: "ella.evans@mail.com",
      phone: "+31 612 345 678",
      role: "User",
      joinedOn: "28.06.2023",
      location: "Amsterdam, NL",
      userStatus: "Finished",
    },
    {
      id: "21",
      username: "lucas.king",
      email: "lucas.king@mail.com",
      phone: "+1 212 7890",
      role: "Admin",
      joinedOn: "19.07.2023",
      location: "New York, NY",
      userStatus: "Active",
    },
    {
      id: "22",
      username: "amelia.scott",
      email: "amelia.scott@mail.com",
      phone: "+33 689 123 456",
      role: "User",
      joinedOn: "11.05.2023",
      location: "Lyon, FR",
      userStatus: "Pending",
    },
    {
      id: "23",
      username: "henry.green",
      email: "henry.green@mail.com",
      phone: "+1 917 6543",
      role: "Manager",
      joinedOn: "02.09.2023",
      location: "Miami, FL",
      userStatus: "Banned",
    },
    {
      id: "24",
      username: "grace.baker",
      email: "grace.baker@mail.com",
      phone: "+1 503 2345",
      role: "Editor",
      joinedOn: "10.01.2024",
      location: "Portland, OR",
      userStatus: "Active",
    },
    {
      id: "25",
      username: "sebastian.morris",
      email: "sebastian.morris@mail.com",
      phone: "+1 213 7654",
      role: "User",
      joinedOn: "22.03.2023",
      location: "Los Angeles, CA",
      userStatus: "Finished",
    },
    {
      id: "26",
      username: "zoe.hall",
      email: "zoe.hall@mail.com",
      phone: "+1 646 4321",
      role: "Manager",
      joinedOn: "05.12.2023",
      location: "New York, NY",
      userStatus: "Pending",
    },
    {
      id: "27",
      username: "jackson.allen",
      email: "jackson.allen@mail.com",
      phone: "+1 718 2345",
      role: "User",
      joinedOn: "09.06.2023",
      location: "Brooklyn, NY",
      userStatus: "Active",
    },
    {
      id: "28",
      username: "aria.young",
      email: "aria.young@mail.com",
      phone: "+1 917 9876",
      role: "Editor",
      joinedOn: "16.08.2023",
      location: "New Jersey, NJ",
      userStatus: "Finished",
    },
    {
      id: "29",
      username: "matthew.hernandez",
      email: "matthew.hernandez@mail.com",
      phone: "+1 646 3456",
      role: "Admin",
      joinedOn: "30.10.2023",
      location: "New York, NY",
      userStatus: "Active",
    },
    {
      id: "30",
      username: "harper.carter",
      email: "harper.carter@mail.com",
      phone: "+1 917 4567",
      role: "User",
      joinedOn: "07.07.2023",
      location: "Queens, NY",
      userStatus: "Pending",
    },
  ];
};

const UsersPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Users</h1>
        <DataTable data={data} columns={columns} />
      </div>
    </div>
  );
};
export default UsersPage;
